application-properties:
  mode: OFFLINE
  size: 10
parser:
  offline-dir: src/main/resources/Offline/
  headers-file: src/main/resources/headers.json
  get-chart-template: /lists/movies/top250/year--DATE
  title-css-class: styles_mainTitle__IFQyZ
  rating-css-class: styles_kinopoiskValue__9qXjg
  votes-css-class: styles_kinopoiskCount__2_VPQ
  secondary-text-css-class: desktop-list-main-info_secondaryText__M_aus
spring:
  datasource:
    url: jdbc:h2:file:./data/kinopoisk
    username: app
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true